# Generated by Django 5.0.3 on 2024-05-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Precio',
            field=models.IntegerField(),
        ),
    ]
