# Generated by Django 5.0.3 on 2024-05-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_menu_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Descuento',
            field=models.IntegerField(default=0),
        ),
    ]
