# Generated by Django 5.0.3 on 2024-05-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_menu_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
