# Generated by Django 5.0.3 on 2024-05-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_alter_menu_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Descuento',
            field=models.IntegerField(default=0),
        ),
    ]
