# Generated by Django 5.0.3 on 2024-05-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_alter_menu_descuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Nombre_platillo',
            new_name='Nombre',
        ),
    ]
