# Generated by Django 5.0.3 on 2024-05-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_rename_nombre_platillo_menu_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cetgaoria', models.CharField(max_length=60)),
            ],
        ),
    ]
