# Generated by Django 5.0.3 on 2024-05-21 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_categoria_platillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categoria',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria_platillo',
            name='nombre_cetgaoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menu'),
        ),
    ]
