# Generated by Django 5.0.3 on 2024-05-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0008_menu_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('rfc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria_platillo',
            name='nombre_cetgaoria',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='menu',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.categoria_platillo'),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('comentario', models.CharField(max_length=400)),
                ('precio_total', models.IntegerField()),
                ('id_mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.mesero')),
                ('id_platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.orden')),
            ],
        ),
    ]
