# Generated by Django 5.0.2 on 2024-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Menu", "0009_mesero_alter_categoria_platillo_nombre_cetgaoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesa",
            name="numero_mesa",
            field=models.IntegerField(default=0),
        ),
    ]
