# Generated by Django 5.0.3 on 2024-05-24 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0012_orden_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria_platillo',
            old_name='nombre_cetgaoria',
            new_name='nombre_categoria',
        ),
    ]
