# Generated by Django 5.0.3 on 2024-05-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0013_rename_nombre_cetgaoria_categoria_platillo_nombre_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
