# Generated by Django 5.0.3 on 2024-05-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0014_alter_orden_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='precio_total',
        ),
    ]
